"""Initial schema with core models

Revision ID: 8e9c1ccc6af9
Revises:
Create Date: 2025-08-14 05:47:18.839988+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8e9c1ccc6af9"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # For SQLite compatibility, we'll use native_enum=False
    # This creates CHECK constraints instead of ENUM types

    # Define enum types for SQLite compatibility
    org_status_enum = sa.Enum(
        "ACTIVE", "SUSPENDED", "TRIAL", "CANCELLED", name="org_status", native_enum=False
    )
    billing_plan_enum = sa.Enum(
        "FREE", "STARTER", "GROWTH", "ENTERPRISE", name="billing_plan", native_enum=False
    )

    op.create_table(
        "org",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("status", org_status_enum, nullable=False),
        sa.Column("billing_plan", billing_plan_enum, nullable=False),
        sa.Column("id", sa.CHAR(32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("org", schema=None) as batch_op:
        # Using standard B-tree index for SQLite compatibility instead of GIN
        batch_op.create_index("idx_org_name", ["name"], unique=False)
        batch_op.create_index(batch_op.f("ix_org_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_org_id"), ["id"], unique=False)

    # Define brain_status enum for SQLite compatibility
    brain_status_enum = sa.Enum(
        "ACTIVE", "DRAFT", "ARCHIVED", name="brain_status", native_enum=False
    )

    op.create_table(
        "brain",
        sa.Column("org_id", sa.CHAR(32), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("niche", sa.String(length=100), nullable=False, comment="Primary business niche"),
        sa.Column(
            "subniche",
            sa.String(length=100),
            nullable=True,
            comment="Optional sub-niche for more specific categorization",
        ),
        sa.Column("status", brain_status_enum, nullable=False),
        sa.Column(
            "config",
            sa.JSON(),
            server_default="{}",
            nullable=False,
            comment="JSON configuration for this brain",
        ),
        sa.Column("id", sa.CHAR(32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        # Removed CHECK constraint with subquery for SQLite compatibility
        # The constraint will be enforced at the application level instead
        sa.ForeignKeyConstraint(["org_id"], ["org.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("brain", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_brain_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_brain_id"), ["id"], unique=False)
        batch_op.create_index(batch_op.f("ix_brain_org_id"), ["org_id"], unique=False)
        # Using a standard unique index for SQLite compatibility
        # Note: The partial index condition (status != 'ARCHIVED') will be enforced at the application level
        batch_op.create_index("uq_brain_org_niche", ["org_id", "niche", "subniche"], unique=True)

    op.create_table(
        "config_audit",
        sa.Column("org_id", sa.CHAR(32), nullable=True),
        sa.Column(
            "actor_type",
            sa.String(length=20),
            nullable=False,
            comment="Type of actor (system, user, api, etc.)",
        ),
        sa.Column(
            "actor_id",
            sa.String(length=100),
            nullable=True,
            comment="ID of the actor (user ID, API key, etc.)",
        ),
        sa.Column(
            "key_path",
            sa.String(length=255),
            nullable=False,
            comment="Dot-notation path of the changed config key",
        ),
        sa.Column(
            "scope",
            sa.String(length=50),
            nullable=False,
            comment="Scope of the change (global, org:ID, brain:ID)",
        ),
        sa.Column(
            "old_hash",
            sa.String(length=64),
            nullable=True,
            comment="SHA-256 hash of the old config value",
        ),
        sa.Column(
            "new_hash",
            sa.String(length=64),
            nullable=False,
            comment="SHA-256 hash of the new config value",
        ),
        sa.Column("note", sa.Text(), nullable=True, comment="Optional note about the change"),
        sa.Column(
            "timestamp",
            sa.DateTime(timezone=True),
            server_default=sa.text("(now())"),
            nullable=False,
            comment="When the change occurred",
        ),
        sa.Column("id", sa.CHAR(32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["org_id"], ["org.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("config_audit", schema=None) as batch_op:
        batch_op.create_index("idx_config_audit_key_scope", ["key_path", "scope"], unique=False)
        batch_op.create_index("idx_config_audit_timestamp", ["timestamp"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_config_audit_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_config_audit_id"), ["id"], unique=False)
        batch_op.create_index(batch_op.f("ix_config_audit_org_id"), ["org_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_config_audit_timestamp"), ["timestamp"], unique=False)

    op.create_table(
        "supplier",
        sa.Column("org_id", sa.CHAR(32), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "region",
            sa.String(length=50),
            nullable=False,
            comment="Supplier's primary region (NA, EU, ASIA, etc.)",
        ),
        sa.Column(
            "api_ref",
            sa.JSON(),
            server_default="{}",
            nullable=False,
            comment="API reference data (tokens, endpoints, etc.)",
        ),
        sa.Column("id", sa.CHAR(32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["org_id"], ["org.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("org_id", "name", name="uq_supplier_org_name"),
    )
    with op.batch_alter_table("supplier", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_supplier_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_supplier_id"), ["id"], unique=False)
        batch_op.create_index(batch_op.f("ix_supplier_org_id"), ["org_id"], unique=False)

    op.create_table(
        "audit_log",
        sa.Column(
            "org_id", sa.CHAR(32), nullable=True, comment="Organization ID (null for system events)"
        ),
        sa.Column("brain_id", sa.CHAR(32), nullable=True, comment="Brain ID (if applicable)"),
        sa.Column(
            "actor_type",
            sa.String(length=20),
            nullable=False,
            comment="Type of actor (system, user, api, etc.)",
        ),
        sa.Column(
            "actor_id",
            sa.String(length=100),
            nullable=True,
            comment="ID of the actor (user ID, API key, etc.)",
        ),
        sa.Column(
            "actor_name",
            sa.String(length=255),
            nullable=True,
            comment="Name of the actor (for display)",
        ),
        sa.Column(
            "action", sa.String(length=30), nullable=False, comment="Type of action performed"
        ),
        sa.Column(
            "entity_type", sa.String(length=50), nullable=False, comment="Type of entity affected"
        ),
        sa.Column("entity_id", sa.CHAR(32), nullable=True, comment="ID of the affected entity"),
        sa.Column("delta", sa.JSON(), nullable=True, comment="JSON diff of changes (for updates)"),
        sa.Column(
            "ip_address", sa.String(length=45), nullable=True, comment="IP address of the actor"
        ),
        sa.Column("user_agent", sa.Text(), nullable=True, comment="User agent string"),
        sa.Column(
            "request_id", sa.String(length=100), nullable=True, comment="Correlation/request ID"
        ),
        sa.Column(
            "timestamp",
            sa.DateTime(timezone=True),
            server_default=sa.text("(now())"),
            nullable=False,
            comment="When the action occurred",
        ),
        sa.Column("id", sa.CHAR(32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["brain_id"], ["brain.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["org_id"], ["org.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("audit_log", schema=None) as batch_op:
        batch_op.create_index(
            "idx_audit_log_actor", ["actor_type", "actor_id", "timestamp"], unique=False
        )
        batch_op.create_index(
            "idx_audit_log_entity", ["entity_type", "entity_id", "timestamp"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_audit_log_action"), ["action"], unique=False)
        batch_op.create_index(batch_op.f("ix_audit_log_brain_id"), ["brain_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_audit_log_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_audit_log_entity_id"), ["entity_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_audit_log_entity_type"), ["entity_type"], unique=False)
        batch_op.create_index(batch_op.f("ix_audit_log_id"), ["id"], unique=False)
        batch_op.create_index(batch_op.f("ix_audit_log_org_id"), ["org_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_audit_log_request_id"), ["request_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_audit_log_timestamp"), ["timestamp"], unique=False)

    # Define order_status_enum for SQLite compatibility
    order_status_enum = sa.Enum(
        "PENDING",
        "PROCESSING",
        "SHIPPED",
        "DELIVERED",
        "CANCELLED",
        "RETURNED",
        name="order_status",
        native_enum=False,
    )

    op.create_table(
        "order",
        sa.Column("org_id", sa.CHAR(32), nullable=False),
        sa.Column("brain_id", sa.CHAR(32), nullable=False),
        sa.Column("channel", sa.String(length=20), nullable=False, comment="Sales channel"),
        sa.Column(
            "order_ref", sa.String(length=100), nullable=False, comment="Channel's order reference"
        ),
        sa.Column(
            "buyer",
            sa.JSON(),
            server_default="{}",
            nullable=False,
            comment="Minimal buyer info (region/city/state only)",
        ),
        sa.Column(
            "ship_to_region",
            sa.String(length=100),
            nullable=False,
            comment="Destination region for tax/fulfillment",
        ),
        sa.Column(
            "items_total_cents",
            sa.Integer(),
            nullable=False,
            comment="Subtotal in cents (sum of item prices)",
        ),
        sa.Column(
            "shipping_total_cents", sa.Integer(), nullable=False, comment="Shipping cost in cents"
        ),
        sa.Column("tax_total_cents", sa.Integer(), nullable=False, comment="Tax amount in cents"),
        sa.Column(
            "tax_model", sa.String(length=30), nullable=False, comment="How taxes are handled"
        ),
        sa.Column("fees_total_cents", sa.Integer(), nullable=False, comment="Total fees in cents"),
        sa.Column(
            "net_revenue_cents",
            sa.Integer(),
            nullable=False,
            comment="Net revenue in cents (items + shipping + tax - fees)",
        ),
        sa.Column("status", order_status_enum, nullable=False, comment="Current order status"),
        sa.Column(
            "placed_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="When the order was placed",
        ),
        sa.Column("id", sa.CHAR(32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("fees_total_cents >= 0", name="chk_order_non_negative_fees"),
        sa.CheckConstraint("items_total_cents > 0", name="chk_order_positive_items_total"),
        sa.CheckConstraint("shipping_total_cents >= 0", name="chk_order_non_negative_shipping"),
        sa.CheckConstraint("tax_total_cents >= 0", name="chk_order_non_negative_tax"),
        sa.ForeignKeyConstraint(["brain_id"], ["brain.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["org_id"], ["org.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("channel", "order_ref", name="uq_order_channel_ref"),
    )
    with op.batch_alter_table("order", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_order_brain_id"), ["brain_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_order_channel"), ["channel"], unique=False)
        batch_op.create_index(batch_op.f("ix_order_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_order_id"), ["id"], unique=False)
        batch_op.create_index(batch_op.f("ix_order_order_ref"), ["order_ref"], unique=False)
        batch_op.create_index(batch_op.f("ix_order_org_id"), ["org_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_order_placed_at"), ["placed_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_order_status"), ["status"], unique=False)

    # Define product_status_enum for SQLite compatibility
    product_status_enum = sa.Enum(
        "DRAFT", "ACTIVE", "ARCHIVED", "DISCONTINUED", name="product_status", native_enum=False
    )

    op.create_table(
        "product",
        sa.Column("org_id", sa.CHAR(32), nullable=False),
        sa.Column("brain_id", sa.CHAR(32), nullable=False),
        sa.Column(
            "sku", sa.String(length=100), nullable=False, comment="Internal stock keeping unit"
        ),
        sa.Column(
            "asin",
            sa.String(length=10),
            nullable=True,
            comment="Amazon Standard Identification Number",
        ),
        sa.Column("upc", sa.String(length=12), nullable=True, comment="Universal Product Code"),
        sa.Column("ean", sa.String(length=13), nullable=True, comment="European Article Number"),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("brand", sa.String(length=100), nullable=True),
        sa.Column(
            "category", sa.String(length=100), nullable=True, comment="Primary product category"
        ),
        sa.Column("weight_g", sa.Integer(), nullable=True, comment="Weight in grams"),
        sa.Column(
            "dim_cm", sa.JSON(), nullable=False, comment="Dimensions in cm: {length, width, height}"
        ),
        sa.Column(
            "attrs",
            sa.JSON(),
            server_default="{}",
            nullable=False,
            comment="Additional product attributes",
        ),
        sa.Column("status", product_status_enum, nullable=False, comment="Current product status"),
        sa.Column("id", sa.CHAR(32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        # Note: Removed JSON validation for SQLite compatibility
        # The application should validate the dimensions JSON structure and values
        sa.CheckConstraint("weight_g IS NULL OR weight_g > 0", name="chk_product_weight_positive"),
        sa.ForeignKeyConstraint(["brain_id"], ["brain.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["org_id"], ["org.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("org_id", "brain_id", "sku", name="uq_product_org_brain_sku"),
    )
    with op.batch_alter_table("product", schema=None) as batch_op:
        # Using standard B-tree indexes for SQLite compatibility instead of GIN
        # Note: Full-text search and JSONB indexing will be limited in SQLite
        batch_op.create_index("idx_product_title_brand", ["title", "brand"], unique=False)
        batch_op.create_index(batch_op.f("ix_product_asin"), ["asin"], unique=True)
        batch_op.create_index(batch_op.f("ix_product_brain_id"), ["brain_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_product_brand"), ["brand"], unique=False)
        batch_op.create_index(batch_op.f("ix_product_category"), ["category"], unique=False)
        batch_op.create_index(batch_op.f("ix_product_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_product_ean"), ["ean"], unique=False)
        batch_op.create_index(batch_op.f("ix_product_id"), ["id"], unique=False)
        batch_op.create_index(batch_op.f("ix_product_org_id"), ["org_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_product_upc"), ["upc"], unique=False)

    # Define listing_status_enum for SQLite compatibility
    listing_status_enum = sa.Enum(
        "DRAFT", "ACTIVE", "INACTIVE", "DELETED", name="listing_status", native_enum=False
    )

    op.create_table(
        "channel_listing",
        sa.Column("org_id", sa.CHAR(32), nullable=False),
        sa.Column("brain_id", sa.CHAR(32), nullable=False),
        sa.Column("product_id", sa.CHAR(32), nullable=False),
        sa.Column("channel", sa.String(length=20), nullable=False, comment="Sales channel"),
        sa.Column(
            "listing_ref",
            sa.String(length=100),
            nullable=False,
            comment="Channel's ID for this listing",
        ),
        sa.Column(
            "price_cents", sa.Integer(), nullable=False, comment="Current listing price in cents"
        ),
        sa.Column(
            "currency", sa.String(length=3), nullable=False, comment="ISO 4217 currency code"
        ),
        sa.Column(
            "fulfillment",
            sa.String(length=10),
            nullable=False,
            comment="How this product is fulfilled",
        ),
        sa.Column("status", listing_status_enum, nullable=False, comment="Listing status"),
        sa.Column(
            "last_published_at",
            sa.DateTime(),
            nullable=True,
            comment="When this listing was last published to the channel",
        ),
        sa.Column(
            "last_checked_at",
            sa.DateTime(),
            nullable=True,
            comment="When this listing was last checked/updated from the channel",
        ),
        sa.Column("id", sa.CHAR(32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        # Simplified currency check for SQLite compatibility
        sa.CheckConstraint(
            "LENGTH(currency) = 3 AND UPPER(currency) = currency", name="chk_listing_valid_currency"
        ),
        sa.CheckConstraint("price_cents > 0", name="chk_listing_positive_price"),
        sa.ForeignKeyConstraint(["brain_id"], ["brain.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["org_id"], ["org.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["product_id"], ["product.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("channel", "listing_ref", name="uq_channel_listing_ref"),
    )
    with op.batch_alter_table("channel_listing", schema=None) as batch_op:
        batch_op.create_index(
            "idx_channel_listing_product_channel", ["product_id", "channel"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_channel_listing_brain_id"), ["brain_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_channel_listing_channel"), ["channel"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_channel_listing_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_channel_listing_id"), ["id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_channel_listing_last_checked_at"), ["last_checked_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_channel_listing_org_id"), ["org_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_channel_listing_product_id"), ["product_id"], unique=False
        )

    # Define fulfillment_status_enum for SQLite compatibility
    fulfillment_status_enum = sa.Enum(
        "PENDING",
        "SHIPPED",
        "DELIVERED",
        "CANCELLED",
        "RETURNED",
        name="fulfillment_status",
        native_enum=False,
    )

    op.create_table(
        "fulfillment",
        sa.Column("order_id", sa.CHAR(32), nullable=False),
        sa.Column("status", fulfillment_status_enum, nullable=False),
        sa.Column("carrier", sa.String(length=100), nullable=True, comment="Shipping carrier"),
        sa.Column(
            "service", sa.String(length=100), nullable=True, comment="Shipping service level"
        ),
        sa.Column("tracking_no", sa.String(length=100), nullable=True, comment="Tracking number"),
        sa.Column("tracking_url", sa.String(length=500), nullable=True, comment="Tracking URL"),
        sa.Column(
            "shipped_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="When the order was shipped",
        ),
        sa.Column(
            "delivered_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="When the order was delivered",
        ),
        sa.Column("id", sa.CHAR(32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["order_id"], ["order.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("fulfillment", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_fulfillment_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_fulfillment_id"), ["id"], unique=False)
        batch_op.create_index(batch_op.f("ix_fulfillment_order_id"), ["order_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_fulfillment_status"), ["status"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_fulfillment_tracking_no"), ["tracking_no"], unique=False
        )
        # Using a standard unique index for SQLite compatibility
        # Note: The partial index condition (tracking_no IS NOT NULL) will be enforced at the application level
        batch_op.create_index("uq_fulfillment_tracking_no", ["tracking_no"], unique=True)

    # Define inventory_event_type_enum for SQLite compatibility
    inventory_event_type_enum = sa.Enum(
        "PURCHASE_ORDER",
        "SALE",
        "RETURN",
        "ADJUSTMENT",
        "DAMAGED",
        "FOUND",
        "LOST",
        "TRANSFER_IN",
        "TRANSFER_OUT",
        "CYCLE_COUNT",
        name="inventory_event_type",
        native_enum=False,
    )

    op.create_table(
        "inventory_event",
        sa.Column(
            "org_id",
            sa.CHAR(32),
            nullable=False,
            comment="Part of composite primary key for partitioning",
        ),
        sa.Column("product_id", sa.CHAR(32), nullable=False, comment="Product that was changed"),
        sa.Column(
            "event_type",
            inventory_event_type_enum,
            nullable=False,
            comment="Type of inventory event (ingest, adjust, sale, return, etc.)",
        ),
        sa.Column(
            "delta",
            sa.Integer(),
            nullable=False,
            comment="Change in quantity (positive or negative)",
        ),
        sa.Column(
            "source",
            sa.String(length=50),
            nullable=False,
            comment="Source of the event (system, api, manual, etc.)",
        ),
        sa.Column(
            "reference_id",
            sa.CHAR(32),
            nullable=True,
            comment="Reference to related entity (order_id, return_id, etc.)",
        ),
        sa.Column(
            "reference_type",
            sa.String(length=50),
            nullable=True,
            comment="Type of reference (order, return, adjustment, etc.)",
        ),
        sa.Column(
            "metadata",
            sa.JSON(),
            server_default="{}",
            nullable=False,
            comment="Additional event metadata",
        ),
        sa.Column(
            "timestamp",
            sa.DateTime(timezone=True),
            server_default=sa.text("(now())"),
            nullable=False,
            comment="When the event occurred",
        ),
        sa.Column("id", sa.CHAR(32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("delta != 0", name="chk_inventory_event_non_zero_delta"),
        sa.ForeignKeyConstraint(["org_id"], ["org.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["product_id"], ["product.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("inventory_event", schema=None) as batch_op:
        batch_op.create_index(
            "idx_inventory_event_product_timestamp", ["product_id", "timestamp"], unique=False
        )
        batch_op.create_index(
            "idx_inventory_event_reference", ["reference_type", "reference_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_inventory_event_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_inventory_event_event_type"), ["event_type"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_inventory_event_id"), ["id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_inventory_event_product_id"), ["product_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_inventory_event_timestamp"), ["timestamp"], unique=False
        )

    op.create_table(
        "order_item",
        sa.Column("order_id", sa.CHAR(32), nullable=False),
        sa.Column("product_id", sa.CHAR(32), nullable=True),
        sa.Column(
            "sku", sa.String(length=100), nullable=False, comment="Product SKU at time of order"
        ),
        sa.Column(
            "name", sa.String(length=500), nullable=False, comment="Product name at time of order"
        ),
        sa.Column("qty", sa.Integer(), nullable=False, comment="Quantity ordered"),
        sa.Column("unit_price_cents", sa.Integer(), nullable=False, comment="Unit price in cents"),
        sa.Column(
            "total_price_cents",
            sa.Integer(),
            nullable=False,
            comment="Total price in cents (qty * unit_price)",
        ),
        sa.Column("fees_cents", sa.Integer(), nullable=False, comment="Fees in cents"),
        sa.Column("cost_cents", sa.Integer(), nullable=False, comment="Unit cost in cents"),
        sa.Column(
            "est_ship_cents",
            sa.Integer(),
            nullable=False,
            comment="Estimated shipping cost in cents",
        ),
        sa.Column(
            "tax_cents", sa.Integer(), nullable=False, server_default="0", comment="Tax in cents"
        ),
        sa.Column("id", sa.CHAR(32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("cost_cents >= 0", name="chk_order_item_non_negative_cost"),
        sa.CheckConstraint("est_ship_cents >= 0", name="chk_order_item_non_negative_est_ship"),
        sa.CheckConstraint("fees_cents >= 0", name="chk_order_item_non_negative_fees"),
        sa.CheckConstraint("qty > 0", name="chk_order_item_positive_qty"),
        sa.CheckConstraint("tax_cents >= 0", name="chk_order_item_non_negative_tax"),
        sa.ForeignKeyConstraint(["order_id"], ["order.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("order_item", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_order_item_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_order_item_id"), ["id"], unique=False)
        batch_op.create_index(batch_op.f("ix_order_item_order_id"), ["order_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_order_item_product_id"), ["product_id"], unique=False)

    op.create_table(
        "return",
        sa.Column("order_id", sa.CHAR(32), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("reason", sa.String(length=255), nullable=False, comment="Reason for return"),
        sa.Column(
            "rma_no",
            sa.String(length=100),
            nullable=True,
            comment="Return Merchandise Authorization number",
        ),
        sa.Column(
            "refunded_cents", sa.Integer(), nullable=True, comment="Amount refunded in cents"
        ),
        sa.Column("notes", sa.Text(), nullable=True, comment="Additional notes"),
        sa.Column(
            "requested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(now())"),
            nullable=False,
            comment="When the return was requested",
        ),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="When the return was received",
        ),
        sa.Column("id", sa.CHAR(32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["order_id"], ["order.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("rma_no"),
    )
    with op.batch_alter_table("return", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_return_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_return_id"), ["id"], unique=False)
        batch_op.create_index(batch_op.f("ix_return_order_id"), ["order_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_return_status"), ["status"], unique=False)

    op.create_table(
        "supplier_offer",
        sa.Column("org_id", sa.CHAR(32), nullable=False),
        sa.Column("brain_id", sa.CHAR(32), nullable=False),
        sa.Column("product_id", sa.CHAR(32), nullable=False),
        sa.Column("supplier_id", sa.CHAR(32), nullable=False),
        sa.Column("sku", sa.String(length=100), nullable=False, comment="Supplier SKU"),
        sa.Column(
            "status", sa.String(length=20), nullable=False, comment="active, inactive, discontinued"
        ),
        sa.Column(
            "lead_time_days", sa.Integer(), nullable=True, comment="Estimated lead time in days"
        ),
        sa.Column("moq", sa.Integer(), nullable=True, comment="Minimum order quantity"),
        sa.Column(
            "price_breaks",
            sa.JSON(),
            server_default="{}",
            nullable=False,
            comment="Tiered pricing {qty: price_cents}",
        ),
        sa.Column("pack_qty", sa.Integer(), nullable=True, comment="Items per pack/case"),
        sa.Column("weight_grams", sa.Integer(), nullable=True, comment="Weight per unit in grams"),
        sa.Column(
            "dimensions_mm",
            sa.JSON(),
            server_default="{}",
            nullable=False,
            comment="{length: int, width: int, height: int} in mm",
        ),
        sa.Column("notes", sa.Text(), nullable=True, comment="Additional notes"),
        sa.Column(
            "cost_cents",
            sa.Integer(),
            nullable=False,
            server_default="0",
            comment="Unit cost in cents",
        ),
        sa.Column(
            "stock", sa.Integer(), nullable=False, server_default="0", comment="Current stock level"
        ),
        sa.Column(
            "last_sync_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Last sync timestamp with supplier",
        ),
        sa.Column("id", sa.CHAR(32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("cost_cents > 0", name="chk_supplier_offer_positive_cost"),
        sa.CheckConstraint("lead_time_days >= 0", name="chk_supplier_offer_lead_time"),
        sa.CheckConstraint("stock >= 0", name="chk_supplier_offer_non_negative_stock"),
        sa.ForeignKeyConstraint(["brain_id"], ["brain.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["org_id"], ["org.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["product_id"], ["product.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["supplier_id"], ["supplier.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("supplier_id", "sku", name="uq_supplier_offer_supplier_sku"),
    )
    with op.batch_alter_table("supplier_offer", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_supplier_offer_brain_id"), ["brain_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_supplier_offer_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_supplier_offer_id"), ["id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_supplier_offer_last_sync_at"), ["last_sync_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_supplier_offer_org_id"), ["org_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_supplier_offer_product_id"), ["product_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_supplier_offer_supplier_id"), ["supplier_id"], unique=False
        )

    op.create_table(
        "price_history",
        sa.Column(
            "org_id",
            sa.CHAR(32),
            nullable=False,
            comment="Part of composite primary key for partitioning",
        ),
        sa.Column("listing_id", sa.CHAR(32), nullable=False),
        sa.Column("price_cents", sa.Integer(), nullable=False, comment="Price in cents"),
        sa.Column(
            "buybox", sa.Boolean(), nullable=False, comment="Whether this price won the buybox"
        ),
        sa.Column(
            "comp_best_cents",
            sa.Integer(),
            nullable=True,
            comment="Best competitor price in cents (if known)",
        ),
        sa.Column(
            "source",
            sa.String(length=20),
            nullable=False,
            comment="Source of this price (spapi, manual, keepa, etc.)",
        ),
        sa.Column(
            "recorded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(now())"),
            nullable=False,
            comment="When this price was recorded",
        ),
        sa.Column(
            "meta",
            sa.JSON(),
            server_default="{}",
            nullable=False,
            comment="Additional price metadata",
        ),
        sa.Column("id", sa.CHAR(32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("price_cents > 0", name="chk_price_history_positive_price"),
        sa.ForeignKeyConstraint(["listing_id"], ["channel_listing.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["org_id"], ["org.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("price_history", schema=None) as batch_op:
        batch_op.create_index(
            "idx_price_history_listing_recorded", ["listing_id", "recorded_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_price_history_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_price_history_id"), ["id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_price_history_listing_id"), ["listing_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_price_history_recorded_at"), ["recorded_at"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("price_history", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_price_history_recorded_at"))
        batch_op.drop_index(batch_op.f("ix_price_history_listing_id"))
        batch_op.drop_index(batch_op.f("ix_price_history_id"))
        batch_op.drop_index(batch_op.f("ix_price_history_created_at"))
        batch_op.drop_index("idx_price_history_listing_recorded")

    op.drop_table("price_history")
    with op.batch_alter_table("supplier_offer", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_supplier_offer_supplier_id"))
        batch_op.drop_index(batch_op.f("ix_supplier_offer_product_id"))
        batch_op.drop_index(batch_op.f("ix_supplier_offer_org_id"))
        batch_op.drop_index(batch_op.f("ix_supplier_offer_last_sync_at"))
        batch_op.drop_index(batch_op.f("ix_supplier_offer_id"))
        batch_op.drop_index(batch_op.f("ix_supplier_offer_created_at"))
        batch_op.drop_index(batch_op.f("ix_supplier_offer_brain_id"))

    op.drop_table("supplier_offer")
    with op.batch_alter_table("return", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_return_status"))
        batch_op.drop_index(batch_op.f("ix_return_order_id"))
        batch_op.drop_index(batch_op.f("ix_return_id"))
        batch_op.drop_index(batch_op.f("ix_return_created_at"))

    op.drop_table("return")
    with op.batch_alter_table("order_item", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_order_item_product_id"))
        batch_op.drop_index(batch_op.f("ix_order_item_order_id"))
        batch_op.drop_index(batch_op.f("ix_order_item_id"))
        batch_op.drop_index(batch_op.f("ix_order_item_created_at"))

    op.drop_table("order_item")
    with op.batch_alter_table("inventory_event", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_inventory_event_timestamp"))
        batch_op.drop_index(batch_op.f("ix_inventory_event_product_id"))
        batch_op.drop_index(batch_op.f("ix_inventory_event_id"))
        batch_op.drop_index(batch_op.f("ix_inventory_event_event_type"))
        batch_op.drop_index(batch_op.f("ix_inventory_event_created_at"))
        batch_op.drop_index("idx_inventory_event_reference")
        batch_op.drop_index("idx_inventory_event_product_timestamp")

    op.drop_table("inventory_event")
    with op.batch_alter_table("fulfillment", schema=None) as batch_op:
        batch_op.drop_index("uq_fulfillment_tracking_no")
        batch_op.drop_index(batch_op.f("ix_fulfillment_tracking_no"))
        batch_op.drop_index(batch_op.f("ix_fulfillment_status"))
        batch_op.drop_index(batch_op.f("ix_fulfillment_order_id"))
        batch_op.drop_index(batch_op.f("ix_fulfillment_id"))
        batch_op.drop_index(batch_op.f("ix_fulfillment_created_at"))

    op.drop_table("fulfillment")
    with op.batch_alter_table("channel_listing", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_channel_listing_product_id"))
        batch_op.drop_index(batch_op.f("ix_channel_listing_org_id"))
        batch_op.drop_index(batch_op.f("ix_channel_listing_last_checked_at"))
        batch_op.drop_index(batch_op.f("ix_channel_listing_id"))
        batch_op.drop_index(batch_op.f("ix_channel_listing_created_at"))
        batch_op.drop_index(batch_op.f("ix_channel_listing_channel"))
        batch_op.drop_index(batch_op.f("ix_channel_listing_brain_id"))
        batch_op.drop_index("idx_channel_listing_product_channel")

    op.drop_table("channel_listing")
    with op.batch_alter_table("product", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_product_upc"))
        batch_op.drop_index(batch_op.f("ix_product_org_id"))
        batch_op.drop_index(batch_op.f("ix_product_id"))
        batch_op.drop_index(batch_op.f("ix_product_ean"))
        batch_op.drop_index(batch_op.f("ix_product_created_at"))
        batch_op.drop_index(batch_op.f("ix_product_category"))
        batch_op.drop_index(batch_op.f("ix_product_brand"))
        batch_op.drop_index(batch_op.f("ix_product_brain_id"))
        batch_op.drop_index(batch_op.f("ix_product_asin"))
        # Remove the standard index that replaced the GIN index
        batch_op.drop_index("idx_product_title_brand")

    op.drop_table("product")
    with op.batch_alter_table("order", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_order_status"))
        batch_op.drop_index(batch_op.f("ix_order_placed_at"))
        batch_op.drop_index(batch_op.f("ix_order_org_id"))
        batch_op.drop_index(batch_op.f("ix_order_order_ref"))
        batch_op.drop_index(batch_op.f("ix_order_id"))
        batch_op.drop_index(batch_op.f("ix_order_created_at"))
        batch_op.drop_index(batch_op.f("ix_order_channel"))
        batch_op.drop_index(batch_op.f("ix_order_brain_id"))

    op.drop_table("order")
    with op.batch_alter_table("audit_log", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_log_timestamp"))
        batch_op.drop_index(batch_op.f("ix_audit_log_request_id"))
        batch_op.drop_index(batch_op.f("ix_audit_log_org_id"))
        batch_op.drop_index(batch_op.f("ix_audit_log_id"))
        batch_op.drop_index(batch_op.f("ix_audit_log_entity_type"))
        batch_op.drop_index(batch_op.f("ix_audit_log_entity_id"))
        batch_op.drop_index(batch_op.f("ix_audit_log_created_at"))
        batch_op.drop_index(batch_op.f("ix_audit_log_brain_id"))
        batch_op.drop_index(batch_op.f("ix_audit_log_action"))
        batch_op.drop_index("idx_audit_log_entity")
        batch_op.drop_index("idx_audit_log_actor")

    op.drop_table("audit_log")
    with op.batch_alter_table("supplier", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_supplier_org_id"))
        batch_op.drop_index(batch_op.f("ix_supplier_id"))
        batch_op.drop_index(batch_op.f("ix_supplier_created_at"))

    op.drop_table("supplier")
    with op.batch_alter_table("config_audit", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_config_audit_timestamp"))
        batch_op.drop_index(batch_op.f("ix_config_audit_org_id"))
        batch_op.drop_index(batch_op.f("ix_config_audit_id"))
        batch_op.drop_index(batch_op.f("ix_config_audit_created_at"))
        batch_op.drop_index("idx_config_audit_timestamp")
        batch_op.drop_index("idx_config_audit_key_scope")

    op.drop_table("config_audit")
    with op.batch_alter_table("brain", schema=None) as batch_op:
        batch_op.drop_index("uq_brain_org_niche")
        batch_op.drop_index(batch_op.f("ix_brain_org_id"))
        batch_op.drop_index(batch_op.f("ix_brain_id"))
        batch_op.drop_index(batch_op.f("ix_brain_created_at"))

    op.drop_table("brain")
    with op.batch_alter_table("org", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_org_id"))
        batch_op.drop_index(batch_op.f("ix_org_created_at"))
        batch_op.drop_index("idx_org_name")

    op.drop_table("org")
    # ### end Alembic commands ###
