"""phase3 schema

Revision ID: afc38cf36a3d
Revises: 061edfd5cfd8
Create Date: 2025-08-17 22:49:21.691787+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy import inspect
from sqlalchemy.dialects import sqlite

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "afc38cf36a3d"
down_revision: Union[str, Sequence[str], None] = "061edfd5cfd8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    _insp = inspect(op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    # Skipped dropping indexes/tables for 'channel_listings' on SQLite where indexes may not exist
    # (Legacy cleanup; safe to no-op)
    # SQLite-safe drop for supplier_offer (skip index drops if absent)
    op.execute("DROP TABLE IF EXISTS supplier_offer")
    # SQLite-safe legacy cleanup
    op.execute("DROP TABLE IF EXISTS fulfillment")
    op.execute("DROP TABLE IF EXISTS order_item")
    # Skipped dropping partitioned table 'inventory_event' to preserve Phase 3 partitioning
    # (Managed by revision 061edfd5cfd8)
    op.execute("DROP TABLE IF EXISTS return")
    op.execute("DROP TABLE IF EXISTS competitors")
    op.execute("DROP TABLE IF EXISTS supplier")
    op.execute("DROP TABLE IF EXISTS channel_listing")
    op.execute("DROP TABLE IF EXISTS product")
    op.execute("DROP TABLE IF EXISTS org")
    op.execute("DROP TABLE IF EXISTS pricing_simulations")
    op.execute('DROP TABLE IF EXISTS "order"')
    op.execute("DROP TABLE IF EXISTS sales")
    op.execute("DROP TABLE IF EXISTS brain")
    # Skipped dropping partitioned table 'price_history' to preserve Phase 3 partitioning
    # (Managed by revision 061edfd5cfd8)
    # Skipped dropping partitioned table 'audit_log' to preserve Phase 3 partitioning
    # (Managed by revision 061edfd5cfd8)
    op.execute("DROP TABLE IF EXISTS config_audit")
    # SQLite-safe: clean up any leftover Alembic temp tables from prior failed runs
    op.execute("DROP TABLE IF EXISTS _alembic_tmp_addresses")
    if _insp.has_table("addresses"):
        with op.batch_alter_table("addresses", schema=None) as batch_op:
            batch_op.add_column(sa.Column("is_default", sa.Boolean(), nullable=False))
            batch_op.alter_column("first_name", existing_type=sa.VARCHAR(), nullable=True)
            batch_op.alter_column("last_name", existing_type=sa.VARCHAR(), nullable=True)

    op.execute("DROP TABLE IF EXISTS _alembic_tmp_categories")
    if _insp.has_table("categories"):
        with op.batch_alter_table("categories", schema=None) as batch_op:
            batch_op.alter_column("slug", existing_type=sa.VARCHAR(length=100), nullable=True)

    op.execute("DROP TABLE IF EXISTS _alembic_tmp_customers")
    if _insp.has_table("customers"):
        with op.batch_alter_table("customers", schema=None) as batch_op:
            batch_op.alter_column(
                "default_shipping_address_id",
                existing_type=sa.NUMERIC(),
                type_=sa.UUID(),
                existing_nullable=True,
            )
            batch_op.alter_column(
                "default_billing_address_id",
                existing_type=sa.NUMERIC(),
                type_=sa.UUID(),
                existing_nullable=True,
            )

    op.execute("DROP TABLE IF EXISTS _alembic_tmp_order_items")
    if _insp.has_table("order_items"):
        with op.batch_alter_table("order_items", schema=None) as batch_op:
            batch_op.alter_column(
                "product_name", existing_type=sa.VARCHAR(length=255), nullable=True
            )
            batch_op.alter_column("sku", existing_type=sa.VARCHAR(length=100), nullable=True)
            batch_op.alter_column(
                "original_price", existing_type=sa.NUMERIC(precision=10, scale=2), nullable=True
            )

    op.execute("DROP TABLE IF EXISTS _alembic_tmp_orders")
    if _insp.has_table("orders"):
        with op.batch_alter_table("orders", schema=None) as batch_op:
            batch_op.alter_column(
                "order_number", existing_type=sa.VARCHAR(length=50), nullable=True
            )
            batch_op.alter_column(
                "customer_email", existing_type=sa.VARCHAR(length=255), nullable=True
            )

    op.execute("DROP TABLE IF EXISTS _alembic_tmp_pricing_snapshots")
    if _insp.has_table("pricing_snapshots"):
        with op.batch_alter_table("pricing_snapshots", schema=None) as batch_op:
            batch_op.add_column(sa.Column("price", sa.Float(), nullable=False))
            batch_op.add_column(sa.Column("cost", sa.Float(), nullable=True))
            batch_op.add_column(sa.Column("competitor_prices", sa.JSON(), nullable=False))
            batch_op.alter_column("source", existing_type=sa.VARCHAR(length=50), nullable=True)
            batch_op.alter_column(
                "base_price", existing_type=sa.NUMERIC(precision=10, scale=2), nullable=True
            )

    op.execute("DROP TABLE IF EXISTS _alembic_tmp_product_reviews")
    if _insp.has_table("product_reviews"):
        with op.batch_alter_table("product_reviews", schema=None) as batch_op:
            batch_op.add_column(sa.Column("comment", sa.Text(), nullable=False))
            batch_op.drop_column("content")

    op.execute("DROP TABLE IF EXISTS _alembic_tmp_products")
    if _insp.has_table("products"):
        with op.batch_alter_table("products", schema=None) as batch_op:
            batch_op.add_column(sa.Column("name", sa.String(length=255), nullable=False))
            batch_op.add_column(sa.Column("description", sa.Text(), nullable=True))
            batch_op.add_column(sa.Column("price", sa.Float(), nullable=False))
            batch_op.add_column(
                sa.Column("cost_price", sa.Numeric(precision=10, scale=2), nullable=True)
            )
            batch_op.add_column(sa.Column("quantity", sa.Integer(), nullable=False))
            batch_op.add_column(sa.Column("upc", sa.String(length=50), nullable=True))
            batch_op.add_column(sa.Column("ean", sa.String(length=50), nullable=True))
            batch_op.add_column(sa.Column("isbn", sa.String(length=50), nullable=True))
            batch_op.add_column(sa.Column("model", sa.String(length=100), nullable=True))
            batch_op.add_column(sa.Column("weight", sa.Float(), nullable=True))
            batch_op.add_column(sa.Column("length", sa.Float(), nullable=True))
            batch_op.add_column(sa.Column("width", sa.Float(), nullable=True))
            batch_op.add_column(sa.Column("height", sa.Float(), nullable=True))
            batch_op.add_column(sa.Column("category_id", sa.Integer(), nullable=True))
            batch_op.add_column(sa.Column("supplier_id", sa.Integer(), nullable=True))
            batch_op.add_column(sa.Column("stock_quantity", sa.Integer(), nullable=False))
            batch_op.add_column(sa.Column("reorder_point", sa.Integer(), nullable=False))
            batch_op.add_column(sa.Column("is_active", sa.Boolean(), nullable=False))
            batch_op.add_column(sa.Column("is_featured", sa.Boolean(), nullable=False))
            batch_op.add_column(sa.Column("is_physical", sa.Boolean(), nullable=False))
            batch_op.add_column(sa.Column("download_url", sa.String(length=255), nullable=True))
            batch_op.add_column(sa.Column("download_limit", sa.Integer(), nullable=True))
            batch_op.add_column(sa.Column("metadata", sa.JSON(), nullable=True))
            batch_op.alter_column(
                "sku",
                existing_type=sa.VARCHAR(length=64),
                type_=sa.String(length=100),
                existing_nullable=False,
            )
        batch_op.alter_column(
            "brand",
            existing_type=sa.VARCHAR(length=128),
            type_=sa.String(length=100),
            existing_nullable=True,
        )
        batch_op.drop_index("ix_products_asin")
        batch_op.drop_constraint("uq_products_sku", type_="unique")
        batch_op.drop_index("ix_products_sku")
        batch_op.create_index(batch_op.f("ix_products_sku"), ["sku"], unique=True)
        batch_op.create_index(batch_op.f("ix_products_brand"), ["brand"], unique=False)
        batch_op.create_index(batch_op.f("ix_products_ean"), ["ean"], unique=False)
        batch_op.create_index(batch_op.f("ix_products_is_active"), ["is_active"], unique=False)
        batch_op.create_index(batch_op.f("ix_products_is_featured"), ["is_featured"], unique=False)
        batch_op.create_index(batch_op.f("ix_products_isbn"), ["isbn"], unique=False)
        batch_op.create_index(batch_op.f("ix_products_name"), ["name"], unique=False)
        batch_op.create_index(batch_op.f("ix_products_upc"), ["upc"], unique=False)
        # Name FKs explicitly to satisfy SQLite batch mode
        batch_op.create_foreign_key(
            "fk_products_category_id", "categories", ["category_id"], ["id"]
        )
        batch_op.create_foreign_key("fk_products_supplier_id", "suppliers", ["supplier_id"], ["id"])
        batch_op.drop_column("title")
        batch_op.drop_column("asin")
        batch_op.drop_column("images")

    op.execute("DROP TABLE IF EXISTS _alembic_tmp_suppliers")
    if _insp.has_table("suppliers"):
        with op.batch_alter_table("suppliers", schema=None) as batch_op:
            batch_op.add_column(sa.Column("name", sa.String(length=255), nullable=False))
            batch_op.add_column(sa.Column("code", sa.String(length=50), nullable=True))
            batch_op.add_column(sa.Column("contact_name", sa.String(length=255), nullable=True))
            batch_op.add_column(sa.Column("contact_email", sa.String(length=255), nullable=True))
            batch_op.add_column(sa.Column("contact_phone", sa.String(length=50), nullable=True))
            batch_op.add_column(sa.Column("company", sa.String(length=255), nullable=True))
            batch_op.add_column(sa.Column("tax_number", sa.String(length=100), nullable=True))
            batch_op.add_column(sa.Column("website", sa.String(length=255), nullable=True))
            batch_op.add_column(sa.Column("address_line1", sa.String(length=255), nullable=True))
            batch_op.add_column(sa.Column("address_line2", sa.String(length=255), nullable=True))
            batch_op.add_column(sa.Column("city", sa.String(length=100), nullable=True))
            batch_op.add_column(sa.Column("state", sa.String(length=100), nullable=True))
            batch_op.add_column(sa.Column("postal_code", sa.String(length=20), nullable=True))
            batch_op.add_column(sa.Column("country", sa.String(length=100), nullable=True))
            batch_op.add_column(sa.Column("lead_time_days", sa.Integer(), nullable=True))
            batch_op.add_column(sa.Column("payment_terms", sa.Integer(), nullable=False))
            batch_op.add_column(sa.Column("is_active", sa.Boolean(), nullable=False))
            batch_op.add_column(sa.Column("is_approved", sa.Boolean(), nullable=False))
            batch_op.add_column(
                sa.Column("credit_limit", sa.Numeric(precision=12, scale=2), nullable=True)
            )
            batch_op.add_column(
                sa.Column("current_balance", sa.Numeric(precision=12, scale=2), nullable=False)
            )
            batch_op.add_column(sa.Column("notes", sa.Text(), nullable=True))
            batch_op.add_column(sa.Column("metadata", sa.JSON(), nullable=True))
            batch_op.add_column(sa.Column("created_at", sa.DateTime(), nullable=False))
            batch_op.add_column(sa.Column("updated_at", sa.DateTime(), nullable=False))
            batch_op.add_column(sa.Column("approved_at", sa.DateTime(), nullable=True))
            batch_op.drop_index("ix_suppliers_product_supplier")
            batch_op.drop_index("ix_suppliers_supplier_name")
            batch_op.drop_index("ix_suppliers_supplier_sku")
            batch_op.drop_constraint("uq_supplier_sku", type_="unique")
            batch_op.create_index(batch_op.f("ix_suppliers_code"), ["code"], unique=True)
            batch_op.create_index(
                batch_op.f("ix_suppliers_contact_email"), ["contact_email"], unique=False
            )
            batch_op.create_index(batch_op.f("ix_suppliers_is_active"), ["is_active"], unique=False)
            batch_op.create_index(
                batch_op.f("ix_suppliers_is_approved"), ["is_approved"], unique=False
            )
            batch_op.create_index(batch_op.f("ix_suppliers_name"), ["name"], unique=False)
            # Skip dropping unnamed foreign key in SQLite batch mode
            # (handled by table recreation semantics if applicable)
            batch_op.drop_column("meta")
            batch_op.drop_column("lead_time_hours")
            batch_op.drop_column("stock_qty")
            batch_op.drop_column("supplier_name")
            batch_op.drop_column("supplier_sku")
            batch_op.drop_column("cost")
            batch_op.drop_column("ships_from")
            batch_op.drop_column("product_id")
            batch_op.drop_column("active")

    op.execute("DROP TABLE IF EXISTS _alembic_tmp_users")
    if _insp.has_table("users"):
        with op.batch_alter_table("users", schema=None) as batch_op:
            batch_op.alter_column("username", existing_type=sa.VARCHAR(length=50), nullable=True)

    # --- Ensure pluralized ecommerce tables exist for fresh DBs (SQLite-safe) ---
    # products
    if not _insp.has_table("products"):
        op.create_table(
            "products",
            sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True, nullable=False),
            sa.Column("sku", sa.String(length=64), nullable=False),
            sa.Column("asin", sa.String(length=20), nullable=True),
            sa.Column("title", sa.String(length=512), nullable=False),
            sa.Column("brand", sa.String(length=128), nullable=True),
            sa.Column("images", sqlite.JSON(), nullable=True),
            sa.Column(
                "created_at",
                sa.DateTime(),
                nullable=False,
                server_default=sa.text("(CURRENT_TIMESTAMP)"),
            ),
            sa.Column(
                "updated_at",
                sa.DateTime(),
                nullable=False,
                server_default=sa.text("(CURRENT_TIMESTAMP)"),
            ),
            sa.UniqueConstraint("sku", name="uq_products_sku"),
        )
        with op.batch_alter_table("products", schema=None) as batch_op:
            batch_op.create_index(batch_op.f("ix_products_sku"), ["sku"], unique=False)
            batch_op.create_index(batch_op.f("ix_products_asin"), ["asin"], unique=False)
            batch_op.create_index(batch_op.f("ix_products_brand"), ["brand"], unique=False)

    # channel_listings
    if not _insp.has_table("channel_listings"):
        op.create_table(
            "channel_listings",
            sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True, nullable=False),
            sa.Column("channel", sa.String(length=32), nullable=False),
            sa.Column(
                "product_id",
                sa.Integer(),
                sa.ForeignKey("products.id", ondelete="CASCADE"),
                nullable=False,
            ),
            sa.Column("listing_ref", sa.String(length=128), nullable=True),
            sa.Column("status", sa.String(length=32), nullable=False, server_default="draft"),
            sa.Column("price", sa.Float(), nullable=True),
            sa.Column("shipping_rule", sa.String(length=64), nullable=True),
            sa.Column(
                "updated_at",
                sa.DateTime(),
                nullable=False,
                server_default=sa.text("(CURRENT_TIMESTAMP)"),
            ),
        )
        with op.batch_alter_table("channel_listings", schema=None) as batch_op:
            batch_op.create_index(
                "ix_channel_listings_prod_channel", ["product_id", "channel"], unique=False
            )
            batch_op.create_index(
                batch_op.f("ix_channel_listings_channel"), ["channel"], unique=False
            )
            batch_op.create_index(
                batch_op.f("ix_channel_listings_listing_ref"), ["listing_ref"], unique=False
            )
            batch_op.create_index(
                batch_op.f("ix_channel_listings_updated_at"), ["updated_at"], unique=False
            )

    # suppliers (maps SupplierOffer ORM)
    if not _insp.has_table("suppliers"):
        op.create_table(
            "suppliers",
            sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True, nullable=False),
            sa.Column("supplier_name", sa.String(length=128), nullable=False),
            sa.Column("supplier_sku", sa.String(length=128), nullable=False),
            sa.Column(
                "product_id",
                sa.Integer(),
                sa.ForeignKey("products.id", ondelete="CASCADE"),
                nullable=False,
            ),
            sa.Column("cost", sa.Float(), nullable=False),
            sa.Column("stock_qty", sa.Integer(), nullable=False, server_default="0"),
            sa.Column("lead_time_hours", sa.Integer(), nullable=False, server_default="48"),
            sa.Column("ships_from", sa.String(length=64), nullable=True),
            sa.Column("active", sa.Boolean(), nullable=False, server_default=sa.text("1")),
            sa.Column("meta", sqlite.JSON(), nullable=True),
            sa.UniqueConstraint("supplier_name", "supplier_sku", name="uq_supplier_sku"),
        )
        with op.batch_alter_table("suppliers", schema=None) as batch_op:
            batch_op.create_index(
                "ix_suppliers_product_supplier", ["product_id", "supplier_name"], unique=False
            )
            batch_op.create_index(
                batch_op.f("ix_suppliers_supplier_name"), ["supplier_name"], unique=False
            )
            batch_op.create_index(
                batch_op.f("ix_suppliers_supplier_sku"), ["supplier_sku"], unique=False
            )

    # competitors
    if not _insp.has_table("competitors"):
        op.create_table(
            "competitors",
            sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True, nullable=False),
            sa.Column(
                "product_id",
                sa.Integer(),
                sa.ForeignKey("products.id", ondelete="CASCADE"),
                nullable=False,
            ),
            sa.Column("channel", sa.String(length=32), nullable=False),
            sa.Column("asin", sa.String(length=20), nullable=True),
            sa.Column("seller", sa.String(length=128), nullable=True),
            sa.Column("price", sa.Float(), nullable=False),
            sa.Column(
                "observed_at",
                sa.DateTime(),
                nullable=False,
                server_default=sa.text("(CURRENT_TIMESTAMP)"),
            ),
        )
        with op.batch_alter_table("competitors", schema=None) as batch_op:
            batch_op.create_index(
                "ix_competitors_product_channel", ["product_id", "channel"], unique=False
            )
            batch_op.create_index(batch_op.f("ix_competitors_channel"), ["channel"], unique=False)
            batch_op.create_index(batch_op.f("ix_competitors_asin"), ["asin"], unique=False)
            batch_op.create_index(
                batch_op.f("ix_competitors_observed_at"), ["observed_at"], unique=False
            )

    # price_history (only if not partitioned version exists)
    if not _insp.has_table("price_history"):
        op.create_table(
            "price_history",
            sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True, nullable=False),
            sa.Column(
                "product_id",
                sa.Integer(),
                sa.ForeignKey("products.id", ondelete="CASCADE"),
                nullable=False,
            ),
            sa.Column("channel", sa.String(length=32), nullable=False),
            sa.Column("price", sa.Float(), nullable=False),
            sa.Column("source", sa.String(length=64), nullable=False),
            sa.Column(
                "recorded_at",
                sa.DateTime(),
                nullable=False,
                server_default=sa.text("(CURRENT_TIMESTAMP)"),
            ),
        )
        with op.batch_alter_table("price_history", schema=None) as batch_op:
            batch_op.create_index(
                batch_op.f("ix_price_history_recorded_at"), ["recorded_at"], unique=False
            )

    # sales
    if not _insp.has_table("sales"):
        op.create_table(
            "sales",
            sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True, nullable=False),
            sa.Column("order_id", sa.String(length=64), nullable=False),
            sa.Column(
                "product_id",
                sa.Integer(),
                sa.ForeignKey("products.id", ondelete="SET NULL"),
                nullable=False,
            ),
            sa.Column("channel", sa.String(length=32), nullable=False),
            sa.Column("sale_price", sa.Float(), nullable=False),
            sa.Column("fees", sa.Float(), nullable=False, server_default="0"),
            sa.Column("shipping_cost", sa.Float(), nullable=False, server_default="0"),
            sa.Column(
                "created_at",
                sa.DateTime(),
                nullable=False,
                server_default=sa.text("(CURRENT_TIMESTAMP)"),
            ),
        )
        with op.batch_alter_table("sales", schema=None) as batch_op:
            batch_op.create_index(batch_op.f("ix_sales_order_id"), ["order_id"], unique=False)
            batch_op.create_index(batch_op.f("ix_sales_channel"), ["channel"], unique=False)
            batch_op.create_index(batch_op.f("ix_sales_created_at"), ["created_at"], unique=False)

    # pricing_simulations
    if not _insp.has_table("pricing_simulations"):
        op.create_table(
            "pricing_simulations",
            sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True, nullable=False),
            sa.Column(
                "product_id",
                sa.Integer(),
                sa.ForeignKey("products.id", ondelete="CASCADE"),
                nullable=False,
            ),
            sa.Column("proposed_price", sa.Float(), nullable=False),
            sa.Column("margin_pct", sa.Float(), nullable=False),
            sa.Column("inputs", sqlite.JSON(), nullable=True),
            sa.Column("status", sa.String(length=32), nullable=False, server_default="pending"),
            sa.Column(
                "created_at",
                sa.DateTime(),
                nullable=False,
                server_default=sa.text("(CURRENT_TIMESTAMP)"),
            ),
        )
        with op.batch_alter_table("pricing_simulations", schema=None) as batch_op:
            batch_op.create_index(
                batch_op.f("ix_pricing_simulations_product_id"), ["product_id"], unique=False
            )
            batch_op.create_index(
                batch_op.f("ix_pricing_simulations_status"), ["status"], unique=False
            )
            batch_op.create_index(
                batch_op.f("ix_pricing_simulations_created_at"), ["created_at"], unique=False
            )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # SQLite-safe: clean up any leftover Alembic temp tables from prior failed runs
    op.execute("DROP TABLE IF EXISTS _alembic_tmp_users")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column("username", existing_type=sa.VARCHAR(length=50), nullable=False)

    with op.batch_alter_table("suppliers", schema=None) as batch_op:
        batch_op.add_column(sa.Column("active", sa.BOOLEAN(), nullable=False))
        batch_op.add_column(sa.Column("product_id", sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column("ships_from", sa.VARCHAR(length=64), nullable=True))
        batch_op.add_column(sa.Column("cost", sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column("supplier_sku", sa.VARCHAR(length=128), nullable=False))
        batch_op.add_column(sa.Column("supplier_name", sa.VARCHAR(length=128), nullable=False))
        batch_op.add_column(sa.Column("stock_qty", sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column("lead_time_hours", sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column("meta", sqlite.JSON(), nullable=True))
        batch_op.create_foreign_key(
            "fk_suppliers_product_id", "products", ["product_id"], ["id"], ondelete="CASCADE"
        )
        batch_op.drop_index(batch_op.f("ix_suppliers_name"))
        batch_op.drop_index(batch_op.f("ix_suppliers_is_approved"))
        batch_op.drop_index(batch_op.f("ix_suppliers_is_active"))
        batch_op.drop_index(batch_op.f("ix_suppliers_contact_email"))
        batch_op.drop_index(batch_op.f("ix_suppliers_code"))
        batch_op.create_unique_constraint("uq_supplier_sku", ["supplier_name", "supplier_sku"])
        batch_op.create_index("ix_suppliers_supplier_sku", ["supplier_sku"], unique=False)
        batch_op.create_index("ix_suppliers_supplier_name", ["supplier_name"], unique=False)
        batch_op.create_index(
            "ix_suppliers_product_supplier", ["product_id", "supplier_name"], unique=False
        )
        batch_op.drop_column("approved_at")
        batch_op.drop_column("updated_at")
        batch_op.drop_column("created_at")
        batch_op.drop_column("metadata")
        batch_op.drop_column("notes")
        batch_op.drop_column("current_balance")
        batch_op.drop_column("credit_limit")
        batch_op.drop_column("is_approved")
        batch_op.drop_column("is_active")
        batch_op.drop_column("payment_terms")
        batch_op.drop_column("lead_time_days")
        batch_op.drop_column("country")
        batch_op.drop_column("postal_code")
        batch_op.drop_column("state")
        batch_op.drop_column("city")
        batch_op.drop_column("address_line2")
        batch_op.drop_column("address_line1")
        batch_op.drop_column("website")
        batch_op.drop_column("tax_number")
        batch_op.drop_column("company")
        batch_op.drop_column("contact_phone")
        batch_op.drop_column("contact_email")
        batch_op.drop_column("contact_name")
        batch_op.drop_column("code")
        batch_op.drop_column("name")

    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.add_column(sa.Column("images", sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column("asin", sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column("title", sa.VARCHAR(length=512), nullable=False))
        batch_op.drop_constraint("fk_products_supplier_id", type_="foreignkey")
        batch_op.drop_constraint("fk_products_category_id", type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_products_upc"))
        batch_op.drop_index(batch_op.f("ix_products_name"))
        batch_op.drop_index(batch_op.f("ix_products_isbn"))
        batch_op.drop_index(batch_op.f("ix_products_is_featured"))
        batch_op.drop_index(batch_op.f("ix_products_is_active"))
        batch_op.drop_index(batch_op.f("ix_products_ean"))
        batch_op.drop_index(batch_op.f("ix_products_brand"))
        batch_op.drop_index(batch_op.f("ix_products_sku"))
        batch_op.create_index("ix_products_sku", ["sku"], unique=False)
        batch_op.create_unique_constraint("uq_products_sku", ["sku"])
        batch_op.create_index("ix_products_asin", ["asin"], unique=False)
        batch_op.alter_column(
            "brand",
            existing_type=sa.String(length=100),
            type_=sa.VARCHAR(length=128),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "sku",
            existing_type=sa.String(length=100),
            type_=sa.VARCHAR(length=64),
            existing_nullable=False,
        )
        batch_op.drop_column("metadata")
        batch_op.drop_column("download_limit")
        batch_op.drop_column("download_url")
        batch_op.drop_column("is_physical")
        batch_op.drop_column("is_featured")
        batch_op.drop_column("is_active")
        batch_op.drop_column("reorder_point")
        batch_op.drop_column("stock_quantity")
        batch_op.drop_column("supplier_id")
        batch_op.drop_column("category_id")
        batch_op.drop_column("height")
        batch_op.drop_column("width")
        batch_op.drop_column("length")
        batch_op.drop_column("weight")
        batch_op.drop_column("model")
        batch_op.drop_column("isbn")
        batch_op.drop_column("ean")
        batch_op.drop_column("upc")
        batch_op.drop_column("quantity")
        batch_op.drop_column("cost_price")
        batch_op.drop_column("price")
        batch_op.drop_column("description")
        batch_op.drop_column("name")

    with op.batch_alter_table("product_reviews", schema=None) as batch_op:
        batch_op.add_column(sa.Column("content", sa.TEXT(), nullable=False))
        batch_op.drop_column("comment")

    with op.batch_alter_table("pricing_snapshots", schema=None) as batch_op:
        batch_op.alter_column(
            "base_price", existing_type=sa.NUMERIC(precision=10, scale=2), nullable=False
        )
        batch_op.alter_column("source", existing_type=sa.VARCHAR(length=50), nullable=False)
        batch_op.drop_column("competitor_prices")
        batch_op.drop_column("cost")
        batch_op.drop_column("price")

    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.alter_column(
            "customer_email", existing_type=sa.VARCHAR(length=255), nullable=False
        )
        batch_op.alter_column("order_number", existing_type=sa.VARCHAR(length=50), nullable=False)

    with op.batch_alter_table("order_items", schema=None) as batch_op:
        batch_op.alter_column(
            "original_price", existing_type=sa.NUMERIC(precision=10, scale=2), nullable=False
        )
        batch_op.alter_column("sku", existing_type=sa.VARCHAR(length=100), nullable=False)
        batch_op.alter_column("product_name", existing_type=sa.VARCHAR(length=255), nullable=False)

    with op.batch_alter_table("customers", schema=None) as batch_op:
        batch_op.alter_column(
            "default_billing_address_id",
            existing_type=sa.UUID(),
            type_=sa.NUMERIC(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "default_shipping_address_id",
            existing_type=sa.UUID(),
            type_=sa.NUMERIC(),
            existing_nullable=True,
        )

    with op.batch_alter_table("categories", schema=None) as batch_op:
        batch_op.alter_column("slug", existing_type=sa.VARCHAR(length=100), nullable=False)

    with op.batch_alter_table("addresses", schema=None) as batch_op:
        batch_op.alter_column("last_name", existing_type=sa.VARCHAR(), nullable=False)
        batch_op.alter_column("first_name", existing_type=sa.VARCHAR(), nullable=False)
        batch_op.drop_column("is_default")

    op.create_table(
        "config_audit",
        sa.Column("org_id", sa.CHAR(length=32), nullable=True),
        sa.Column("actor_type", sa.VARCHAR(length=20), nullable=False),
        sa.Column("actor_id", sa.VARCHAR(length=100), nullable=True),
        sa.Column("key_path", sa.VARCHAR(length=255), nullable=False),
        sa.Column("scope", sa.VARCHAR(length=50), nullable=False),
        sa.Column("old_hash", sa.VARCHAR(length=64), nullable=True),
        sa.Column("new_hash", sa.VARCHAR(length=64), nullable=False),
        sa.Column("note", sa.TEXT(), nullable=True),
        sa.Column("timestamp", sa.DATETIME(), server_default=sa.text("(now())"), nullable=False),
        sa.Column("id", sa.CHAR(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["org_id"], ["org.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("config_audit", schema=None) as batch_op:
        batch_op.create_index("ix_config_audit_timestamp", ["timestamp"], unique=False)
        batch_op.create_index("ix_config_audit_org_id", ["org_id"], unique=False)
        batch_op.create_index("ix_config_audit_id", ["id"], unique=False)
        batch_op.create_index("ix_config_audit_created_at", ["created_at"], unique=False)
        batch_op.create_index("idx_config_audit_timestamp", ["timestamp"], unique=False)
        batch_op.create_index("idx_config_audit_key_scope", ["key_path", "scope"], unique=False)

    # Guard: if audit_log already exists (managed by previous partitioning), skip recreation
    _bind = op.get_bind()
    _insp = inspect(_bind)
    if not _insp.has_table("audit_log"):
        op.create_table(
            "audit_log",
            sa.Column("org_id", sa.CHAR(length=32), nullable=True),
            sa.Column("brain_id", sa.CHAR(length=32), nullable=True),
            sa.Column("actor_type", sa.VARCHAR(length=20), nullable=False),
            sa.Column("actor_id", sa.VARCHAR(length=100), nullable=True),
            sa.Column("actor_name", sa.VARCHAR(length=255), nullable=True),
            sa.Column("action", sa.VARCHAR(length=30), nullable=False),
            sa.Column("entity_type", sa.VARCHAR(length=50), nullable=False),
            sa.Column("entity_id", sa.CHAR(length=32), nullable=True),
            sa.Column("delta", sqlite.JSON(), nullable=True),
            sa.Column("ip_address", sa.VARCHAR(length=45), nullable=True),
            sa.Column("user_agent", sa.TEXT(), nullable=True),
            sa.Column("request_id", sa.VARCHAR(length=100), nullable=True),
            sa.Column(
                "timestamp", sa.DATETIME(), server_default=sa.text("(now())"), nullable=False
            ),
            sa.Column("id", sa.CHAR(length=32), nullable=False),
            sa.Column(
                "created_at",
                sa.DATETIME(),
                server_default=sa.text("(CURRENT_TIMESTAMP)"),
                nullable=False,
            ),
            sa.Column(
                "updated_at",
                sa.DATETIME(),
                server_default=sa.text("(CURRENT_TIMESTAMP)"),
                nullable=False,
            ),
            sa.ForeignKeyConstraint(["brain_id"], ["brain.id"], ondelete="CASCADE"),
            sa.ForeignKeyConstraint(["org_id"], ["org.id"], ondelete="CASCADE"),
            sa.PrimaryKeyConstraint("id"),
        )
        with op.batch_alter_table("audit_log", schema=None) as batch_op:
            batch_op.create_index("ix_audit_log_timestamp", ["timestamp"], unique=False)
            batch_op.create_index("ix_audit_log_request_id", ["request_id"], unique=False)
            batch_op.create_index("ix_audit_log_org_id", ["org_id"], unique=False)
            batch_op.create_index("ix_audit_log_id", ["id"], unique=False)
            batch_op.create_index("ix_audit_log_entity_type", ["entity_type"], unique=False)
            batch_op.create_index("ix_audit_log_entity_id", ["entity_id"], unique=False)
            batch_op.create_index("ix_audit_log_created_at", ["created_at"], unique=False)
            batch_op.create_index("ix_audit_log_brain_id", ["brain_id"], unique=False)
            batch_op.create_index("ix_audit_log_action", ["action"], unique=False)
            batch_op.create_index(
                "idx_audit_log_entity", ["entity_type", "entity_id", "timestamp"], unique=False
            )
            batch_op.create_index(
                "idx_audit_log_actor", ["actor_type", "actor_id", "timestamp"], unique=False
            )

    if not _insp.has_table("price_history"):
        op.create_table(
            "price_history",
            sa.Column("id", sa.INTEGER(), nullable=False),
            sa.Column("product_id", sa.INTEGER(), nullable=False),
            sa.Column("channel", sa.VARCHAR(length=32), nullable=False),
            sa.Column("price", sa.FLOAT(), nullable=False),
            sa.Column("source", sa.VARCHAR(length=64), nullable=False),
            sa.Column("recorded_at", sa.DATETIME(), nullable=False),
            sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="CASCADE"),
            sa.PrimaryKeyConstraint("id"),
        )
        with op.batch_alter_table("price_history", schema=None) as batch_op:
            batch_op.create_index("ix_price_history_recorded_at", ["recorded_at"], unique=False)

    op.create_table(
        "brain",
        sa.Column("org_id", sa.CHAR(length=32), nullable=False),
        sa.Column("name", sa.VARCHAR(length=255), nullable=False),
        sa.Column("niche", sa.VARCHAR(length=100), nullable=False),
        sa.Column("subniche", sa.VARCHAR(length=100), nullable=True),
        sa.Column("status", sa.VARCHAR(length=8), nullable=False),
        sa.Column("config", sqlite.JSON(), server_default=sa.text("'{}'"), nullable=False),
        sa.Column("id", sa.CHAR(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["org_id"], ["org.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("brain", schema=None) as batch_op:
        batch_op.create_index("uq_brain_org_niche", ["org_id", "niche", "subniche"], unique=1)
        batch_op.create_index("ix_brain_org_id", ["org_id"], unique=False)
        batch_op.create_index("ix_brain_id", ["id"], unique=False)
        batch_op.create_index("ix_brain_created_at", ["created_at"], unique=False)

    op.create_table(
        "sales",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("order_id", sa.VARCHAR(length=64), nullable=False),
        sa.Column("product_id", sa.INTEGER(), nullable=False),
        sa.Column("channel", sa.VARCHAR(length=32), nullable=False),
        sa.Column("sale_price", sa.FLOAT(), nullable=False),
        sa.Column("fees", sa.FLOAT(), nullable=False),
        sa.Column("shipping_cost", sa.FLOAT(), nullable=False),
        sa.Column("created_at", sa.DATETIME(), nullable=False),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("sales", schema=None) as batch_op:
        batch_op.create_index("ix_sales_order_id", ["order_id"], unique=False)
        batch_op.create_index("ix_sales_created_at", ["created_at"], unique=False)
        batch_op.create_index("ix_sales_channel", ["channel"], unique=False)

    op.create_table(
        "order",
        sa.Column("org_id", sa.CHAR(length=32), nullable=False),
        sa.Column("brain_id", sa.CHAR(length=32), nullable=False),
        sa.Column("channel", sa.VARCHAR(length=20), nullable=False),
        sa.Column("order_ref", sa.VARCHAR(length=100), nullable=False),
        sa.Column("buyer", sqlite.JSON(), server_default=sa.text("'{}'"), nullable=False),
        sa.Column("ship_to_region", sa.VARCHAR(length=100), nullable=False),
        sa.Column("items_total_cents", sa.INTEGER(), nullable=False),
        sa.Column("shipping_total_cents", sa.INTEGER(), nullable=False),
        sa.Column("tax_total_cents", sa.INTEGER(), nullable=False),
        sa.Column("tax_model", sa.VARCHAR(length=30), nullable=False),
        sa.Column("fees_total_cents", sa.INTEGER(), nullable=False),
        sa.Column("net_revenue_cents", sa.INTEGER(), nullable=False),
        sa.Column("status", sa.VARCHAR(length=10), nullable=False),
        sa.Column("placed_at", sa.DATETIME(), nullable=False),
        sa.Column("id", sa.CHAR(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("fees_total_cents >= 0", name="chk_order_non_negative_fees"),
        sa.CheckConstraint("items_total_cents > 0", name="chk_order_positive_items_total"),
        sa.CheckConstraint("shipping_total_cents >= 0", name="chk_order_non_negative_shipping"),
        sa.CheckConstraint("tax_total_cents >= 0", name="chk_order_non_negative_tax"),
        sa.ForeignKeyConstraint(["brain_id"], ["brain.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["org_id"], ["org.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("channel", "order_ref", name="uq_order_channel_ref"),
    )
    with op.batch_alter_table("order", schema=None) as batch_op:
        batch_op.create_index("ix_order_status", ["status"], unique=False)
        batch_op.create_index("ix_order_placed_at", ["placed_at"], unique=False)
        batch_op.create_index("ix_order_org_id", ["org_id"], unique=False)
        batch_op.create_index("ix_order_order_ref", ["order_ref"], unique=False)
        batch_op.create_index("ix_order_id", ["id"], unique=False)
        batch_op.create_index("ix_order_created_at", ["created_at"], unique=False)
        batch_op.create_index("ix_order_channel", ["channel"], unique=False)
        batch_op.create_index("ix_order_brain_id", ["brain_id"], unique=False)

    op.create_table(
        "pricing_simulations",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("product_id", sa.INTEGER(), nullable=False),
        sa.Column("proposed_price", sa.FLOAT(), nullable=False),
        sa.Column("margin_pct", sa.FLOAT(), nullable=False),
        sa.Column("inputs", sqlite.JSON(), nullable=True),
        sa.Column("status", sa.VARCHAR(length=32), nullable=False),
        sa.Column("created_at", sa.DATETIME(), nullable=False),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("pricing_simulations", schema=None) as batch_op:
        batch_op.create_index("ix_pricing_simulations_status", ["status"], unique=False)
        batch_op.create_index("ix_pricing_simulations_product_id", ["product_id"], unique=False)
        batch_op.create_index("ix_pricing_simulations_created_at", ["created_at"], unique=False)

    op.create_table(
        "org",
        sa.Column("name", sa.VARCHAR(length=255), nullable=False),
        sa.Column("status", sa.VARCHAR(length=9), nullable=False),
        sa.Column("billing_plan", sa.VARCHAR(length=10), nullable=False),
        sa.Column("id", sa.CHAR(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("org", schema=None) as batch_op:
        batch_op.create_index("ix_org_id", ["id"], unique=False)
        batch_op.create_index("ix_org_created_at", ["created_at"], unique=False)
        batch_op.create_index("idx_org_name", ["name"], unique=False)

    op.create_table(
        "product",
        sa.Column("org_id", sa.CHAR(length=32), nullable=False),
        sa.Column("brain_id", sa.CHAR(length=32), nullable=False),
        sa.Column("sku", sa.VARCHAR(length=100), nullable=False),
        sa.Column("asin", sa.VARCHAR(length=10), nullable=True),
        sa.Column("upc", sa.VARCHAR(length=12), nullable=True),
        sa.Column("ean", sa.VARCHAR(length=13), nullable=True),
        sa.Column("title", sa.VARCHAR(length=500), nullable=False),
        sa.Column("brand", sa.VARCHAR(length=100), nullable=True),
        sa.Column("category", sa.VARCHAR(length=100), nullable=True),
        sa.Column("weight_g", sa.INTEGER(), nullable=True),
        sa.Column("dim_cm", sqlite.JSON(), nullable=False),
        sa.Column("attrs", sqlite.JSON(), server_default=sa.text("'{}'"), nullable=False),
        sa.Column("status", sa.VARCHAR(length=12), nullable=False),
        sa.Column("id", sa.CHAR(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("weight_g IS NULL OR weight_g > 0", name="chk_product_weight_positive"),
        sa.ForeignKeyConstraint(["brain_id"], ["brain.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["org_id"], ["org.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("org_id", "brain_id", "sku", name="uq_product_org_brain_sku"),
    )
    with op.batch_alter_table("product", schema=None) as batch_op:
        batch_op.create_index("ix_product_upc", ["upc"], unique=False)
        batch_op.create_index("ix_product_org_id", ["org_id"], unique=False)
        batch_op.create_index("ix_product_id", ["id"], unique=False)
        batch_op.create_index("ix_product_ean", ["ean"], unique=False)
        batch_op.create_index("ix_product_created_at", ["created_at"], unique=False)
        batch_op.create_index("ix_product_category", ["category"], unique=False)
        batch_op.create_index("ix_product_brand", ["brand"], unique=False)
        batch_op.create_index("ix_product_brain_id", ["brain_id"], unique=False)
        batch_op.create_index("ix_product_asin", ["asin"], unique=1)
        batch_op.create_index("idx_product_title_brand", ["title", "brand"], unique=False)

    op.create_table(
        "channel_listing",
        sa.Column("org_id", sa.CHAR(length=32), nullable=False),
        sa.Column("brain_id", sa.CHAR(length=32), nullable=False),
        sa.Column("product_id", sa.CHAR(length=32), nullable=False),
        sa.Column("channel", sa.VARCHAR(length=20), nullable=False),
        sa.Column("listing_ref", sa.VARCHAR(length=100), nullable=False),
        sa.Column("price_cents", sa.INTEGER(), nullable=False),
        sa.Column("currency", sa.VARCHAR(length=3), nullable=False),
        sa.Column("fulfillment", sa.VARCHAR(length=10), nullable=False),
        sa.Column("status", sa.VARCHAR(length=8), nullable=False),
        sa.Column("last_published_at", sa.DATETIME(), nullable=True),
        sa.Column("last_checked_at", sa.DATETIME(), nullable=True),
        sa.Column("id", sa.CHAR(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "LENGTH(currency) = 3 AND UPPER(currency) = currency", name="chk_listing_valid_currency"
        ),
        sa.CheckConstraint("price_cents > 0", name="chk_listing_positive_price"),
        sa.ForeignKeyConstraint(["brain_id"], ["brain.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["org_id"], ["org.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["product_id"], ["product.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("channel", "listing_ref", name="uq_channel_listing_ref"),
    )
    with op.batch_alter_table("channel_listing", schema=None) as batch_op:
        batch_op.create_index("ix_channel_listing_product_id", ["product_id"], unique=False)
        batch_op.create_index("ix_channel_listing_org_id", ["org_id"], unique=False)
        batch_op.create_index(
            "ix_channel_listing_last_checked_at", ["last_checked_at"], unique=False
        )
        batch_op.create_index("ix_channel_listing_id", ["id"], unique=False)
        batch_op.create_index("ix_channel_listing_created_at", ["created_at"], unique=False)
        batch_op.create_index("ix_channel_listing_channel", ["channel"], unique=False)
        batch_op.create_index("ix_channel_listing_brain_id", ["brain_id"], unique=False)
        batch_op.create_index(
            "idx_channel_listing_product_channel", ["product_id", "channel"], unique=False
        )

    op.create_table(
        "supplier",
        sa.Column("org_id", sa.CHAR(length=32), nullable=False),
        sa.Column("name", sa.VARCHAR(length=255), nullable=False),
        sa.Column("region", sa.VARCHAR(length=50), nullable=False),
        sa.Column("api_ref", sqlite.JSON(), server_default=sa.text("'{}'"), nullable=False),
        sa.Column("id", sa.CHAR(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["org_id"], ["org.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("org_id", "name", name="uq_supplier_org_name"),
    )
    with op.batch_alter_table("supplier", schema=None) as batch_op:
        batch_op.create_index("ix_supplier_org_id", ["org_id"], unique=False)
        batch_op.create_index("ix_supplier_id", ["id"], unique=False)
        batch_op.create_index("ix_supplier_created_at", ["created_at"], unique=False)

    op.create_table(
        "competitors",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("product_id", sa.INTEGER(), nullable=False),
        sa.Column("channel", sa.VARCHAR(length=32), nullable=False),
        sa.Column("asin", sa.VARCHAR(length=20), nullable=True),
        sa.Column("seller", sa.VARCHAR(length=128), nullable=True),
        sa.Column("price", sa.FLOAT(), nullable=False),
        sa.Column("observed_at", sa.DATETIME(), nullable=False),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("competitors", schema=None) as batch_op:
        batch_op.create_index(
            "ix_competitors_product_channel", ["product_id", "channel"], unique=False
        )
        batch_op.create_index("ix_competitors_observed_at", ["observed_at"], unique=False)
        batch_op.create_index("ix_competitors_channel", ["channel"], unique=False)
        batch_op.create_index("ix_competitors_asin", ["asin"], unique=False)

    op.create_table(
        "return",
        sa.Column("order_id", sa.CHAR(length=32), nullable=False),
        sa.Column("status", sa.VARCHAR(length=20), nullable=False),
        sa.Column("reason", sa.VARCHAR(length=255), nullable=False),
        sa.Column("rma_no", sa.VARCHAR(length=100), nullable=True),
        sa.Column("refunded_cents", sa.INTEGER(), nullable=True),
        sa.Column("notes", sa.TEXT(), nullable=True),
        sa.Column("requested_at", sa.DATETIME(), server_default=sa.text("(now())"), nullable=False),
        sa.Column("received_at", sa.DATETIME(), nullable=True),
        sa.Column("id", sa.CHAR(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["order_id"], ["order.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("rma_no"),
    )
    with op.batch_alter_table("return", schema=None) as batch_op:
        batch_op.create_index("ix_return_status", ["status"], unique=False)
        batch_op.create_index("ix_return_order_id", ["order_id"], unique=False)
        batch_op.create_index("ix_return_id", ["id"], unique=False)
        batch_op.create_index("ix_return_created_at", ["created_at"], unique=False)

    if not _insp.has_table("inventory_event"):
        op.create_table(
            "inventory_event",
            sa.Column("org_id", sa.CHAR(length=32), nullable=False),
            sa.Column("product_id", sa.CHAR(length=32), nullable=False),
            sa.Column("event_type", sa.VARCHAR(length=14), nullable=False),
            sa.Column("delta", sa.INTEGER(), nullable=False),
            sa.Column("source", sa.VARCHAR(length=50), nullable=False),
            sa.Column("reference_id", sa.CHAR(length=32), nullable=True),
            sa.Column("reference_type", sa.VARCHAR(length=50), nullable=True),
            sa.Column("metadata", sqlite.JSON(), server_default=sa.text("'{}'"), nullable=False),
            sa.Column(
                "timestamp", sa.DATETIME(), server_default=sa.text("(now())"), nullable=False
            ),
            sa.Column("id", sa.CHAR(length=32), nullable=False),
            sa.Column(
                "created_at",
                sa.DATETIME(),
                server_default=sa.text("(CURRENT_TIMESTAMP)"),
                nullable=False,
            ),
            sa.Column(
                "updated_at",
                sa.DATETIME(),
                server_default=sa.text("(CURRENT_TIMESTAMP)"),
                nullable=False,
            ),
            sa.CheckConstraint("delta != 0", name="chk_inventory_event_non_zero_delta"),
            sa.ForeignKeyConstraint(["org_id"], ["org.id"], ondelete="CASCADE"),
            sa.ForeignKeyConstraint(["product_id"], ["product.id"], ondelete="CASCADE"),
            sa.PrimaryKeyConstraint("id"),
        )
        with op.batch_alter_table("inventory_event", schema=None) as batch_op:
            batch_op.create_index("ix_inventory_event_timestamp", ["timestamp"], unique=False)
            batch_op.create_index("ix_inventory_event_product_id", ["product_id"], unique=False)
            batch_op.create_index("ix_inventory_event_id", ["id"], unique=False)
            batch_op.create_index("ix_inventory_event_event_type", ["event_type"], unique=False)
            batch_op.create_index("ix_inventory_event_created_at", ["created_at"], unique=False)
            batch_op.create_index(
                "idx_inventory_event_reference", ["reference_type", "reference_id"], unique=False
            )
            batch_op.create_index(
                "idx_inventory_event_product_timestamp", ["product_id", "timestamp"], unique=False
            )

    op.create_table(
        "order_item",
        sa.Column("order_id", sa.CHAR(length=32), nullable=False),
        sa.Column("product_id", sa.CHAR(length=32), nullable=True),
        sa.Column("sku", sa.VARCHAR(length=100), nullable=False),
        sa.Column("name", sa.VARCHAR(length=500), nullable=False),
        sa.Column("qty", sa.INTEGER(), nullable=False),
        sa.Column("unit_price_cents", sa.INTEGER(), nullable=False),
        sa.Column("total_price_cents", sa.INTEGER(), nullable=False),
        sa.Column("fees_cents", sa.INTEGER(), nullable=False),
        sa.Column("cost_cents", sa.INTEGER(), nullable=False),
        sa.Column("est_ship_cents", sa.INTEGER(), nullable=False),
        sa.Column("tax_cents", sa.INTEGER(), server_default=sa.text("'0'"), nullable=False),
        sa.Column("id", sa.CHAR(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("cost_cents >= 0", name="chk_order_item_non_negative_cost"),
        sa.CheckConstraint("est_ship_cents >= 0", name="chk_order_item_non_negative_est_ship"),
        sa.CheckConstraint("fees_cents >= 0", name="chk_order_item_non_negative_fees"),
        sa.CheckConstraint("qty > 0", name="chk_order_item_positive_qty"),
        sa.CheckConstraint("tax_cents >= 0", name="chk_order_item_non_negative_tax"),
        sa.ForeignKeyConstraint(["order_id"], ["order.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("order_item", schema=None) as batch_op:
        batch_op.create_index("ix_order_item_product_id", ["product_id"], unique=False)
        batch_op.create_index("ix_order_item_order_id", ["order_id"], unique=False)
        batch_op.create_index("ix_order_item_id", ["id"], unique=False)
        batch_op.create_index("ix_order_item_created_at", ["created_at"], unique=False)

    op.create_table(
        "fulfillment",
        sa.Column("order_id", sa.CHAR(length=32), nullable=False),
        sa.Column("status", sa.VARCHAR(length=9), nullable=False),
        sa.Column("carrier", sa.VARCHAR(length=100), nullable=True),
        sa.Column("service", sa.VARCHAR(length=100), nullable=True),
        sa.Column("tracking_no", sa.VARCHAR(length=100), nullable=True),
        sa.Column("tracking_url", sa.VARCHAR(length=500), nullable=True),
        sa.Column("shipped_at", sa.DATETIME(), nullable=True),
        sa.Column("delivered_at", sa.DATETIME(), nullable=True),
        sa.Column("id", sa.CHAR(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["order_id"], ["order.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("fulfillment", schema=None) as batch_op:
        batch_op.create_index("uq_fulfillment_tracking_no", ["tracking_no"], unique=1)
        batch_op.create_index("ix_fulfillment_tracking_no", ["tracking_no"], unique=False)
        batch_op.create_index("ix_fulfillment_status", ["status"], unique=False)
        batch_op.create_index("ix_fulfillment_order_id", ["order_id"], unique=False)
        batch_op.create_index("ix_fulfillment_id", ["id"], unique=False)
        batch_op.create_index("ix_fulfillment_created_at", ["created_at"], unique=False)

    op.create_table(
        "supplier_offer",
        sa.Column("org_id", sa.CHAR(length=32), nullable=False),
        sa.Column("brain_id", sa.CHAR(length=32), nullable=False),
        sa.Column("product_id", sa.CHAR(length=32), nullable=False),
        sa.Column("supplier_id", sa.CHAR(length=32), nullable=False),
        sa.Column("sku", sa.VARCHAR(length=100), nullable=False),
        sa.Column("status", sa.VARCHAR(length=20), nullable=False),
        sa.Column("lead_time_days", sa.INTEGER(), nullable=True),
        sa.Column("moq", sa.INTEGER(), nullable=True),
        sa.Column("price_breaks", sqlite.JSON(), server_default=sa.text("'{}'"), nullable=False),
        sa.Column("pack_qty", sa.INTEGER(), nullable=True),
        sa.Column("weight_grams", sa.INTEGER(), nullable=True),
        sa.Column("dimensions_mm", sqlite.JSON(), server_default=sa.text("'{}'"), nullable=False),
        sa.Column("notes", sa.TEXT(), nullable=True),
        sa.Column("cost_cents", sa.INTEGER(), server_default=sa.text("'0'"), nullable=False),
        sa.Column("stock", sa.INTEGER(), server_default=sa.text("'0'"), nullable=False),
        sa.Column("last_sync_at", sa.DATETIME(), nullable=True),
        sa.Column("id", sa.CHAR(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("cost_cents > 0", name="chk_supplier_offer_positive_cost"),
        sa.CheckConstraint("lead_time_days >= 0", name="chk_supplier_offer_lead_time"),
        sa.CheckConstraint("stock >= 0", name="chk_supplier_offer_non_negative_stock"),
        sa.ForeignKeyConstraint(["brain_id"], ["brain.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["org_id"], ["org.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["product_id"], ["product.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["supplier_id"], ["supplier.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("supplier_id", "sku", name="uq_supplier_offer_supplier_sku"),
    )
    with op.batch_alter_table("supplier_offer", schema=None) as batch_op:
        batch_op.create_index("ix_supplier_offer_supplier_id", ["supplier_id"], unique=False)
        batch_op.create_index("ix_supplier_offer_product_id", ["product_id"], unique=False)
        batch_op.create_index("ix_supplier_offer_org_id", ["org_id"], unique=False)
        batch_op.create_index("ix_supplier_offer_last_sync_at", ["last_sync_at"], unique=False)
        batch_op.create_index("ix_supplier_offer_id", ["id"], unique=False)
        batch_op.create_index("ix_supplier_offer_created_at", ["created_at"], unique=False)
        batch_op.create_index("ix_supplier_offer_brain_id", ["brain_id"], unique=False)

    op.create_table(
        "channel_listings",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("channel", sa.VARCHAR(length=32), nullable=False),
        sa.Column("product_id", sa.INTEGER(), nullable=False),
        sa.Column("listing_ref", sa.VARCHAR(length=128), nullable=True),
        sa.Column("status", sa.VARCHAR(length=32), nullable=False),
        sa.Column("price", sa.FLOAT(), nullable=True),
        sa.Column("shipping_rule", sa.VARCHAR(length=64), nullable=True),
        sa.Column("updated_at", sa.DATETIME(), nullable=False),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("channel_listings", schema=None) as batch_op:
        batch_op.create_index("ix_channel_listings_updated_at", ["updated_at"], unique=False)
        batch_op.create_index(
            "ix_channel_listings_prod_channel", ["product_id", "channel"], unique=False
        )
        batch_op.create_index("ix_channel_listings_listing_ref", ["listing_ref"], unique=False)
        batch_op.create_index("ix_channel_listings_channel", ["channel"], unique=False)

    # ### end Alembic commands ###
